using MermaidGraph.Diagrams;

namespace MermaidGraph;

/// <summary>
/// mermaid-graph.exe
/// </summary>
public sealed class Program
{
    /// <summary>
    /// Outputs a mermaid graph of the dependency diagram for a project, or whole solution.
    /// </summary>
    /// <param name="path">Full path to the solution (*.sln) or project (*.csproj) file that will be mapped.</param>
    /// <param name="type">The type of diagram to generate (e.g., Graph or Class).</param>
    /// <returns>HResult</returns>
    public static int Main(string? path, DiagramType type = DiagramType.Graph)
    {
        if (path is null)
        {
            System.CommandLine.DragonFruit.CommandLine
                .ExecuteAssembly(typeof(AutoGeneratedProgram).Assembly, ["--help"], "");

            return 1;
        }

        var file = new FileInfo(path);
        if (!file.Exists)
        {
            Console.WriteLine($"Error: File not found - {path}");
            return 2;
        }

        try
        {
            if (path.EndsWith(".csproj"))
            {
                Console.WriteLine(Commands.Project(file, type));
                return 0;
            }

            if (path.EndsWith(".sln"))
            {
                Console.WriteLine(Commands.Solution(file, type));
                return 0;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
            return ex.HResult;
        }

        Console.WriteLine($"Error: Unsupported file type - {path}");
        return 3;
    }
}
