namespace MermaidGraph;

// ReSharper disable UnusedMember.Global

/// <summary>
/// mermaid-graph.exe
/// </summary>
public sealed class Program
{
    /// <summary>
    /// Outputs a mermaid graph of the dependency diagram for a project, or whole solution.
    /// </summary>
    /// <param name="path">Full path to the solution (*.sln) or project (*.csproj) file that will be mapped.</param>
    /// <returns>HResult</returns>
    public static int Main(string? path)
    {
        if (path is null)
        {
            System.CommandLine.DragonFruit.CommandLine.ExecuteAssembly(typeof(AutoGeneratedProgram).Assembly, ["--help"], "");
            return 1;
        }
        
        var file = new FileInfo(path);
        if (!file.Exists)
        {
            Console.WriteLine($"Error: File not found - {path}");
            return 2;
        }

        try
        {
            if (path.EndsWith(".csproj"))
            {
                Console.WriteLine(new Commands().Project(file));
                return 0;
            }

            if (path.EndsWith(".sln"))
            {
                Console.WriteLine(new Commands().Solution(file));
                return 0;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
            return ex.HResult;
        }

        Console.WriteLine($"Error: Unsupported file type - {path}");
        return 3;
    }
}